CREATE TABLE USUARIOS (
    ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    USERNAME VARCHAR(50) NOT NULL UNIQUE,
    EMAIL VARCHAR(100) NOT NULL UNIQUE,
    SENHA_HASH CHAR(60) NOT NULL,  -- PARA BCRYPT
    PRIMARY KEY (ID)
);
ALTER TABLE USUARIOS
CHANGE COLUMN ID ID_USUARIO INT UNSIGNED NOT NULL AUTO_INCREMENT;

ALTER TABLE USUARIOS
ADD COLUMN FIRST_NAME VARCHAR(50) NOT NULL;

ALTER TABLE USUARIOS
ADD COLUMN LAST_NAME VARCHAR(50) NOT NULL;

ALTER TABLE USUARIOS
CHANGE COLUMN SENHA_HASH PASSWORD CHAR(60) NOT NULL;
